-- Drop the table if it already exists (Oracle 23c+ syntax)
-- For older versions, you may need to drop it manually or use a PL/SQL block
DROP TABLE gifts CASCADE CONSTRAINTS;

CREATE TABLE gifts (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(255) NOT NULL,
    pricePoint   VARCHAR2(10) NOT NULL,
    audience     VARCHAR2(255) NOT NULL,
    image        VARCHAR2(255) NOT NULL,
    description  CLOB NOT NULL,
    submittedBy  VARCHAR2(255) NOT NULL,
    submittedOn  TIMESTAMP NOT NULL
);

-- Optional: Add a comment to the table for clarity in the Modeler
COMMENT ON TABLE gifts IS 'Table containing gift ideas and metadata for the unearthed app';
